---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "GitHub Action"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

env:
  python_version: "3.12"

jobs:
  ### Test the GitHub Action in this repository ###
  tests:
    name: "Test 🧪"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Perform setup prior to running test(s)
      - name: "Checkout sample project repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: "lfreleng-actions/test-python-project"
          path: "test-python-project"

      - name: "Run action: ${{ github.repository }}"
        uses: ./
        with:
          python_version: "${{ env.python_version }}"
          path_prefix: "test-python-project/"

      - name: "Run action: ${{ github.repository }} [Parallel Tests]"
        uses: ./
        with:
          python_version: "${{ env.python_version }}"
          path_prefix: "test-python-project/"
          parallel_tests: true

      - name: "Run action: ${{ github.repository }} [Install Custom Kernel]"
        uses: ./
        id: install-fail
        continue-on-error: true
        with:
          python_version: "${{ env.python_version }}"
          path_prefix: "test-python-project/"
          nbmake_kernel: "test"
          install_kernel: false

      - name: "Validate previous step failure"
        if: steps.install-fail.outcome == 'success'
        shell: bash
        run: |
          # Check previous step failure
          echo "Error: previous step should have failed ❌"
          exit 1

      - name: "Run action: ${{ github.repository }} [Custom Kernel / Fail]"
        uses: ./
        with:
          python_version: "${{ env.python_version }}"
          path_prefix: "test-python-project/"
          nbmake_kernel: "test"
          install_kernel: true
